#文件1
server:
  port: 5001
spring:
  application:
    name: spring-cloud-portal-gateway
eureka:
  instance:
   prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://admin:1q2w3e4r!@127.0.0.1:1234/eureka/
# prefix 访问前缀
zuul:
  routes: 
    abc: 
      path: /file/**
#      stripPrefix: true
      serviceId: spring-cloud-model
##  stripPrefix: false  ip+/spring-cloud-file-system/hello
