server:
  port: 1003

spring:
  application:
    name: spring-cloud-file-system
  http: 
    multipart:
     max-file-size: 2000Mb
     max-request-size: 2500Mb 	    
#注册中心指向start 不指定当前实例eureka的 instance:  instance-id 和name 此时可以一个服务名称下注册多个实例 
eureka:
  instance: 
    prefer-ip-address: true
  client: 
    service-url: 
#      defaultZone: http://admin:1q2w3e4r!@127.0.0.1:1234/eureka/
      defaultZone: http://peer2:1001/eureka/,http://peer1:1000/eureka/
#注册中心指向end