server:
  port: 7070
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jjc120074203/Config-Server.git
          searchPaths: file1,file2*
          # file1  文件路径
          # file2  文件路径