#1.打开 控制台  通过证书控制器 keytool -genkeypair -alias myspringkey -keyalg RSA -keypass changeme -keystore server.jks -storepass letmein
#2.把server.jks放入代码 resource中
#3.启动 config-server  进入curl控制台 >curl -X  POST http://localhost:7070/encrypt -d 加密数据   生成A
#4.把数据文件中写入'{cipher}+A'
#配置身份认证
server:
  port: 7070
security: 
    basic: 
        enable: true
    user: 
        name: admin
        password: 1q2w3e4r!
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/jjc120074203/Config-Server.git
          uri: git@192.168.1.249:chenjl/Spring-Config-Server.git
          username: 
          password: 
#对阵加密配置
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: myspringkey
    secret: changeme
          