server:
  port: 5000
spring:
  application:
    name: spring-cloud-hystrix-turbine
eureka:
  instance:
    instance-id: spring-cloud-hystrix-turbine
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:1q2w3e4r!@127.0.0.1:1234/eureka/
# 监控
turbine:
  aggregator:
#监控单个
#    clusterConfig: SPRING-CLOUD-PORTAL
#  appConfig: spring-cloud-portal
#监控集群
    clusterConfig: default
  appConfig: spring-cloud-portal,spring-cloud-portal-bak
  clusterNameExpression: "'default'"