package org.spring.cloud.common.aop.annotation;

public enum MessageOperation {
    
	SERVICE_ONLINE, SERVICE_OFFLINE, SERVICE_CLICKNUM,
	COMPONENT_ONLINE, COMPONNET_OFFLINE, COMPONENT_SUBSCRIBENUM,
	API_SUBSCRIBED, API_UN_SUBSCRIBED,CABLE_REGISTER,CABLE_RESTPWD,
	CABLE_SUBSCRIPT_COMPONENT,CABLE_INSTANCE_ARRANGE,CABLE_SERVICE_ONLINE,
	CABLE_SERVICE_OFFLINE,PILOT_REGISTER,PILOT_UPDATEPWD
}
